### ISSUE TITLE
Ask for Windows support

### ISSUE THREAD

**Issue by radifar** [kuelumbus/rdkit_platform_wheels#8]
Hello, this is amazing ❤️ . I just knew this repo from Stackoverflow. I intend to use this as the dependency rather than the one from conda-forge so it gives the flexibility to the user (who is not familiar with anaconda). But unfortunately there is still no support for Windows. Is it possible to add this? I've seen that `pypa/cibuildwheel` GHA supports Windows too.

Thank you.

**Comment by kuelumbus** [comment]
Thanks. I understand. It would be of course good to have windows wheels too. Let me look into this.

**Comment by kuelumbus** [comment]
@radifar  Can you please check if the wheels in the artifact file at https://github.com/kuelumbus/rdkit_platform_wheels/actions/runs/1200348501 work on windows. You would need to download the artifact file, unzip, and install the wheel that matches your python version with something like `python -m pip install rdkit_pypi-2021.3.4-cp38-cp38-win_amd64.whl`.

**Comment by radifar** [comment]
Awesome!

I just give it a try on Windows 10 inside QEMU VM (I'm using Kubuntu btw). My steps are basically like this:

1. Install Python 3.6-3.9 with Python executable installer from python.org
2. Create virtual environment for every version using venv module from Python standard library
3. Install RDKit wheel in each corresponding virtual environment.

The results show that Python 3.8 and 3.9 working just fine. But on Python 3.6 and 3.7 encounter the same problem.

Here is how it goes in Python 3.6:

```
(rdkit-win-36) C:\Users\radif\Documents\Python>pip install rdkit_pypi-2021.3.4-cp36-cp36m-win_amd64.whl
Processing c:\users\radif\documents\python\rdkit_pypi-2021.3.4-cp36-cp36m-win_amd64.whl
Collecting numpy>=1.19 (from rdkit-pypi==2021.3.4)
  Downloading https://files.pythonhosted.org/packages/ea/bc/da526221bc111857c7ef39c3af670bbcf5e69c247b0d22e51986f6d0c5c2/numpy-1.19.5-cp36-cp36m-win_amd64.whl (13.2MB)
    100% |████████████████████████████████| 13.2MB 1.3MB/s
Installing collected packages: numpy, rdkit-pypi
Successfully installed numpy-1.19.5 rdkit-pypi-2021.3.4
You are using pip version 18.1, however version 21.2.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(rdkit-win-36) C:\Users\radif\Documents\Python>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit\__init__.py", line 20, in <module>
    _delvewheel_init_patch_0_0_14()
  File "C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit\__init__.py", line 17, in _delvewheel_init_patch_0_0_14
    WinDLL(os.path.join(libs_dir, lib))
  File "C:\Users\radif\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

Python 3.7

```
(rdkit-win-37) C:\Users\radif\Documents\Python>pip install rdkit_pypi-2021.3.4-cp37-cp37m-win_amd64.whl
Processing c:\users\radif\documents\python\rdkit_pypi-2021.3.4-cp37-cp37m-win_amd64.whl
Collecting numpy>=1.19
  Downloading numpy-1.21.2-cp37-cp37m-win_amd64.whl (14.0 MB)
     |████████████████████████████████| 14.0 MB 135 kB/s
Installing collected packages: numpy, rdkit-pypi
Successfully installed numpy-1.21.2 rdkit-pypi-2021.3.4
WARNING: You are using pip version 20.1.1; however, version 21.2.4 is available.
You should consider upgrading via the 'c:\users\radif\documents\python\rdkit-win-37\scripts\python.exe -m pip install --upgrade pip' command.

(rdkit-win-37) C:\Users\radif\Documents\Python>python
Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\radif\Documents\Python\rdkit-win-37\lib\site-packages\rdkit\__init__.py", line 20, in <module>
    _delvewheel_init_patch_0_0_14()
  File "C:\Users\radif\Documents\Python\rdkit-win-37\lib\site-packages\rdkit\__init__.py", line 17, in _delvewheel_init_patch_0_0_14
    WinDLL(os.path.join(libs_dir, lib))
  File "C:\Users\radif\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

Python 3.8

```
(rdkit-win-38) C:\Users\radif\Documents\Python>pip install rdkit_pypi-2021.3.4-cp38-cp38-win_amd64.whl
Processing c:\users\radif\documents\python\rdkit_pypi-2021.3.4-cp38-cp38-win_amd64.whl
Collecting numpy>=1.19
  Downloading numpy-1.21.2-cp38-cp38-win_amd64.whl (14.0 MB)
     |████████████████████████████████| 14.0 MB 213 kB/s
Installing collected packages: numpy, rdkit-pypi
Successfully installed numpy-1.21.2 rdkit-pypi-2021.3.4
WARNING: You are using pip version 21.1.1; however, version 21.2.4 is available.
You should consider upgrading via the 'c:\users\radif\documents\python\rdkit-win-38\scripts\python.exe -m pip install --upgrade pip' command.

(rdkit-win-38) C:\Users\radif\Documents\Python>python
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdkit
>>> exit()

(rdkit-win-38) C:\Users\radif\Documents\Python>python
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
>>> m = Chem.MolFromSmiles('Cc1ccccc1')
>>> m
<rdkit.Chem.rdchem.Mol object at 0x0000021575174040>
>>> m.GetNumAtoms()
7
```

Python 3.9

```
(rdkit-win-39) C:\Users\radif\Documents\Python>pip install rdkit_pypi-2021.3.4-cp39-cp39-win_amd64.whl
Processing c:\users\radif\documents\python\rdkit_pypi-2021.3.4-cp39-cp39-win_amd64.whl
Collecting numpy>=1.19
  Downloading numpy-1.21.2-cp39-cp39-win_amd64.whl (14.0 MB)
     |████████████████████████████████| 14.0 MB 128 kB/s
Installing collected packages: numpy, rdkit-pypi
Successfully installed numpy-1.21.2 rdkit-pypi-2021.3.4
WARNING: You are using pip version 21.2.3; however, version 21.2.4 is available.
You should consider upgrading via the 'C:\Users\radif\Documents\Python\rdkit-win-39\Scripts\python.exe -m pip install --upgrade pip' command.

(rdkit-win-39) C:\Users\radif\Documents\Python>python
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
>>> m = Chem.MolFromSmiles('Cc1ccccc1')
>>> m
<rdkit.Chem.rdchem.Mol object at 0x000001D7906C6940>
>>> m.GetNumAtoms()
7
```

Upon searching this `OSError: [WinError 126] The specified module could not be found` error message, I find that it is a common problem in Windows, with variety of possible workaround.

**Comment by radifar** [comment]
After further investigation I found something interesting. When I look at `\lib\site-packages\rdkit\__init__.py` I can see that when RDKit runs on Python >= 3.8 it uses different library finding mechanism

`\lib\site-packages\rdkit\__init__.py`
```
def _delvewheel_init_patch_0_0_14():
    import os
    import sys
    libs_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir, 'rdkit_pypi.libs'))
    if sys.version_info[:2] >= (3, 8):
        if os.path.exists(os.path.join(sys.base_prefix, 'conda-meta')):
            os.environ['CONDA_DLL_SEARCH_MODIFICATION_ENABLE']='1'
        os.add_dll_directory(libs_dir)
    else:
        from ctypes import WinDLL
        with open(os.path.join(libs_dir, '.load-order-rdkit_pypi-2021.3.4')) as file:
            load_order = file.read().split()
        for lib in load_order:
            WinDLL(os.path.join(libs_dir, lib))
...

```

Then I'm curious what gonna happen if I change the Python version `(3, 8)` to `(3, 6)`. And when I import RDKit again it shows this

```
(rdkit-win-36) C:\Users\radif\Documents\Python>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from rdkit import Chem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit\__init__.py", line 20, in <module>
    _delvewheel_init_patch_0_0_14()
  File "C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit\__init__.py", line 11, in _delvewheel_init_patch_0_0_14
    os.add_dll_directory(libs_dir)
AttributeError: module 'os' has no attribute 'add_dll_directory'
```

Now I understand why Python 3.6 and 3.7 uses `ctype.WinDLL` instead. Time for some digging into RDKit GitHub repository to find some answer.

**Comment by radifar** [comment]
After lots of trial and error still can't figure out why it doesn't work on Python 3.6 and 3.7. But my current suspicion is that the `--no-dll` option in here is the culprit:

```
delvewheel show -v --no-dll vcruntime140d.dll --add-path C:\libs C:\Users\RUNNER~1\AppData\Local\Temp\cibuildwheeldgkqo1a9\built_wheel\rdkit_pypi-2021.3.5-cp36-cp36m-win_amd64.whl && delvewheel repair -v --no-dll vcruntime140d.dll --add-path C:\libs -w C:\Users\RUNNER~1\AppData\Local\Temp\cibuildwheeldgkqo1a9\repaired_wheel C:\Users\RUNNER~1\AppData\Local\Temp\cibuildwheeldgkqo1a9\built_wheel\rdkit_pypi-2021.3.5-cp36-cp36m-win_amd64.whl
```

**Comment by kuelumbus** [comment]
Thanks for your investigation. Can you please check your `{python_instal_dir}/Libs/site-packages/rdkit_pypi.libs/` directory. This directory should contain the dlls that show "module can not be found". Maybe you can modify 
```
 print(f"{lib} module can not be found")
```
to 
```
 print(f"os.path.join(libs_dir, lib) module can not be found") 
```

and paste the output. I wonder why the DLLs are not there, or why they cannot be found. I checked quickly on my system all versions (3.6, 3.7, 3.8, and 3.9) work.

**Comment by kuelumbus** [comment]
On note on the DLLs with "d" like vcruntime140d.dll and bz2d.dll. I don't understand why they are linked at all because they seem to be necessary for debugging only.

**Comment by radifar** [comment]
After changing that line to this
 
`print(f"{os.path.join(libs_dir, lib)} module can not be found") `

This is what I got
```
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdkit
ucrtbased-203d10b0.dll
C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit_pypi.libs\bz2d-6ed60cba.dll module can not be found
C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit_pypi.libs\zlibd1-19bef9e1.dll module can not be found
C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit_pypi.libs\brotlicommon-c15db6d6.dll module can not be found
iconv-2-05e6fd4e.dll
C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit_pypi.libs\brotlidec-17bf5acb.dll module can not be found
C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit_pypi.libs\libpng16d-a6b57be2.dll module can not be found
C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit_pypi.libs\freetyped-f0dd24a0.dll module can not be found
C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit_pypi.libs\intl-8-609bf870.dll module can not be found
vcruntime140_1.dll
C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit_pypi.libs\libexpatd-be050e5c.dll module can not be found
C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit_pypi.libs\fontconfig-1-2d16370f.dll module can not be found
msvcp140.dll
bz2-1492afc2.dll
C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit_pypi.libs\cairo-2-48df4dfc.dll module can not be found
boost_serialization-vc140-mt-x64-1_67-6ef822c2.dll
zlib1-967d8c51.dll
libpng16-22a77934.dll
C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit_pypi.libs\freetype-bb3ad0ea.dll module can not be found
boost_iostreams-vc140-mt-x64-1_67-3e4ea10a.dll
boost_python36-vc140-mt-x64-1_67-de154df2.dll
```

The DLLs are all there, some of them just won't load. Probably because they depend on another DLL.

I think the problem appear on my Windows and not your is because the differences in Windows system. I am using clean Windows, although that previously I also tried installing `Microsoft Visual C++ 2015-2019 Redistributable (x64) - 14.29.30133` to fix this problem, but to no avail.

PS. also tried installing directly to Python 3.6 installation instead of inside virtual environment and still doesn't work.

**Comment by radifar** [comment]
Yay! I finally figured it out. Turns out I haven't dig deep enough with Dependencies. There is one more file missing, aside from `vcruntime140d.dll` it turns out that `vcruntime140d.dll` require another DLL file, which is `ucrtbased.dll`. And after I have those files in my DLL search path I can finally import RDKit. I assume that you already have those files in your DLL search path (probably `C:\Windows\System32`).

IMO I think we should either include or exclude those two together.

**Comment by radifar** [comment]
So I tried removing the DLLs, then make sure the old rdkit-pypi in Python 3.6 and 3.7 didn't work. Then I uninstall all the rdkit-pypi in various Python version environment. Then I install the new one.

And the result is still not good. Python 3.8 and 3.9 is working fine, but 3.6 and 3.7 showing the following error:
![entry_point_not_found_36](https://user-images.githubusercontent.com/11450417/132717662-faf00107-5b3e-441d-968d-dd7dbbb966a4.png)

here is the error message after I click the OK button:
```
(rdkit-win-36) C:\Users\radif\Documents\Python>python
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import rdkit
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit\__init__.py", line 20, in <module>
    _delvewheel_init_patch_0_0_14()
  File "C:\Users\radif\Documents\Python\rdkit-win-36\lib\site-packages\rdkit\__init__.py", line 17, in _delvewheel_init_patch_0_0_14
    WinDLL(os.path.join(libs_dir, lib))
  File "C:\Users\radif\AppData\Local\Programs\Python\Python36\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 127] The specified procedure could not be found
```

**Comment by kuelumbus** [comment]
Ok, I think I finally figured it out. Can  you please test if the wheels in https://github.com/kuelumbus/rdkit_platform_wheels/actions/runs/1223116204 work? I booted a Windows VM and the RDKit wheels were running fine there.

**Comment by kuelumbus** [comment]
I've just uploaded the wheels to pypi: `pip install rdkit-pypi` should now work on Windows.

**Comment by radifar** [comment]
Whoa! It's working on Python 3.6-3.9 now! Thank you so much. 😃 

How did you work it out? I'm planning to do the same with Openbabel, since my cibuildwheel integration request in openbabel/openbabel#2403 is not getting any respond. I probably can do this for MacOS or Linux build, but building in Windows seems much more complicated. In the past I only have few game building experience using Visual Studio. I can see that you struggle a lot with this build, I would really appreciate it if you could document your build problems and workarounds on a blog post or article perhaps?
